### ISSUE TITLE
数据类型不匹配

### ISSUE THREAD

**Issue by SniperUsopp** [Menooker/KunQuant#3] opened 2024-02-24 13:41 UTC
![WechatIMG1743](https://github.com/Menooker/KunQuant/assets/6157515/5b0ba1cf-6124-4d79-a9a3-53581228d04e)

在KunQuant/cpp/Kun/Ops.hpp:303:31这里，input类型为f32*8, 而v的类型为一个vec_f32*8,这两种不同类型直接进行逻辑运算在编译时会报错。

**Comment by Menooker** [comment] 2024-02-25 04:25
你好，能否贴一下
1. 编译环境（Windows/Linux, 编译器：MSVC/g++/clang，CPU：x64？ARM？支不支持AVX2？）
2. 具体编译器报错

如果编译环境正确，理论上不会出现你说的这个问题。注意到`f32x8`是我对于Intel x64 AVX `__m256`类型的别名：

文件`cpp\Kun\Base.hpp`
```c++
#include <immintrin.h>

namespace kun {
    struct Context;
    using f32x8 = __m256;
}
```

然后`kun_simd::vec_f32x8` 是对于`__m256`的进一步封装，`vec_f32x8`可以由`__m256`(也就是`f32x8`)隐式构造：
文件`cpp\KunSIMD\cpu\f32x8.hpp`:

```c++
template<>
struct alignas(32) vec<float, 8> {
public:
    ...
    INLINE vec(__m256 const &x) { v = x; }
    ....
};
```

所以你报错的`auto cmpless = input < v;` 这行会走到：

`cpp\KunSIMD\cpu\f32x8.hpp`的95行：

```c++
INLINE vec_f32x8 operator<(vec_f32x8 const &a, vec_f32x8 const &b) {
    auto ret = _mm256_cmp_ps(a.v, b.v, _CMP_LT_OQ);
    return ret;
}
```

`input` 会自动转换到`vec_f32x8`

很可能你说的这个编译错误其实不是报出第一个错误？是不是在这个错误之前，编译器报告了例如找不到"immintrin.h" 或者 “__m256"之类的错误？如果出现了这两个错误，说明你的编译器不支持AVX。

**Comment by SniperUsopp** [comment] 2024-02-25 04:44
非常感谢您的耐心解答，我使用的操作系统为MacOS，CPU 为x86-64的酷睿i7，编译器为AppleClang 13.1.6.13160021。可能是由于我的编译环境问题。我再检查下，感谢

**Comment by Menooker** [comment] 2024-02-25 07:11
好的🤝有关macos我可能没法帮很多忙了，我没有复现的环境，请查看一下appleclang需要什么设置才能正确使用avx intrinsic。

如果你解决了问题，欢迎pr/分享解决方案，谢谢🙏

**Comment by Menooker** [comment] 2024-02-25 07:15
我查到xcode12之后会默认同时为x86和arm编译
https://stackoverflow.com/a/66493975

是否需要通过cmake关掉arm target？

**Comment by Menooker** [comment] 2024-02-25 10:54
可以用github actions 复现：https://github.com/Menooker/KunQuant/actions/runs/8037419367/job/21952225798

**Comment by SniperUsopp** [comment] 2024-02-25 10:57
非常感谢，我 C++用的不熟，我学习下

**Comment by Menooker** [comment] 2024-02-25 13:55
看来是apple clang编译器实现和gcc有区别，我看一下怎么解决

**Comment by Menooker** [comment] 2024-02-25 14:55
可以试一下这个branch吗？https://github.com/Menooker/KunQuant/pull/4
应该可以解决你现在的问题

**Comment by SniperUsopp** [comment] 2024-02-25 14:57
> 可以试一下这个branch吗？#4 应该可以解决你现在的问题

我来测试下，太厉害了！！

**Comment by SniperUsopp** [comment] 2024-02-25 15:13
`[  4%] Building CXX object CMakeFiles/KunRunner.dir/cpp/Kun/Executor.cpp.o
[ 14%] Building CXX object CMakeFiles/KunRunner.dir/cpp/Kun/PyBinding.cpp.o
[ 14%] Building CXX object CMakeFiles/KunRunner.dir/cpp/Kun/Rank.cpp.o
[ 19%] Building CXX object CMakeFiles/KunRunner.dir/cpp/Kun/Module.cpp.o
[ 23%] Building CXX object CMakeFiles/KunRunner.dir/cpp/Kun/Runtime.cpp.o
[ 28%] Building CXX object CMakeFiles/KunRunner.dir/cpp/Kun/Scale.cpp.o
[ 33%] Building CXX object CMakeFiles/KunRunner.dir/cpp/KunSIMD/cpu/tables.cpp.o
[ 38%] Linking CXX shared library KunRunner.cpython-310-darwin.so
[ 38%] Built target KunRunner
[ 47%] Generating Alpha101/Alpha101.cpp
[ 47%] Generating Alpha101Selected/Alpha101Selected.cpp
[ 52%] Generating Test/AvgAndStddev.cpp, Test/TestRank.cpp, Test/TestRank2.cpp, Test/TestLog.cpp, Test/TestPow.cpp
Permission denied
Permission denied
Permission denied
gmake[2]: *** [projects/CMakeFiles/Alpha101.dir/build.make:75: projects/Alpha101/Alpha101.cpp] Error 1
gmake[2]: *** [projects/CMakeFiles/Test.dir/build.make:75: projects/Test/AvgAndStddev.cpp] Error 1
gmake[2]: *** [projects/CMakeFiles/Alpha101Selected.dir/build.make:75: projects/Alpha101Selected/Alpha101Selected.cpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:174: projects/CMakeFiles/Alpha101.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:226: projects/CMakeFiles/Test.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:200: projects/CMakeFiles/Alpha101Selected.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
`
编译报错解决了！！但是在执行cmake --build . -- -j4时，报了Permission denied错误。使用sudo权限重新cmake .. 并重新执行cmake --build . -- -j4也不行

**Comment by Menooker** [comment] 2024-02-26 12:18
https://github.com/Menooker/KunQuant/pull/4 更新了，能不能解决你的问题？Github Actions过了

**Comment by SniperUsopp** [comment] 2024-02-27 18:28
> #4 更新了，能不能解决你的问题？Github Actions过了

It do works!! Really appreciate for your help.

**Comment by SniperUsopp** [comment] 2024-02-27 18:35
> #4 更新了，能不能解决你的问题？Github Actions过了

<img width="1537" alt="image" src="https://github.com/Menooker/KunQuant/assets/6157515/1d185405-ea2c-4750-a8b4-640360ecd870">

Oh, sad. After i run 'cmake --build . -- -j4', i can not  see 'projects/Alpha101/{libAlpha101.so, Alpha101.dll} ' in my  build directory. Only can see Alpha101.cpp

**Comment by Menooker** [comment] 2024-02-27 23:27
It is in your screenshot. At projects/libAlpha101.dylib. I will update the path in readme.

**Comment by SniperUsopp** [comment] 2024-03-04 14:31
Thank you very much for your help. I have successfully run the test case. In addition, I want to use Go language or Rust language to make the framework of the outer service, and then use Go language to call the so file, but I see that when KunQuant runs, it needs to use the Python version of KunRunner to execute. I would like to ask if I can use the compiled so file in Go language without relying on Python code.

**Comment by Menooker** [comment] 2024-03-05 00:31
I suppose the C language API is all you need. KunQuant hasnt had that yet, but I will add that later. In Go or Rust, you can always write the binding code for C-API. And the new C-interface will not depend on Python.
Closing this issue because the problem is solved. Welcome to open another for the binding issue.

**Closed by Menooker** 2024-03-05 00:31 UTC

**Comment by Menooker** [comment] 2024-03-05 12:49
> Thank you very much for your help. I have successfully run the test case. In addition, I want to use Go language or Rust language to make the framework of the outer service, and then use Go language to call the so file, but I see that when KunQuant runs, it needs to use the Python version of KunRunner to execute. I would like to ask if I can use the compiled so file in Go language without relying on Python code.

Please try this branch: https://github.com/Menooker/KunQuant/pull/5
You can view the C-API document at https://github.com/Menooker/KunQuant/blob/capi/CAPI.md
